### ISSUE TITLE
Trying to build a VSMP with waveshare 12.48in screen. 

### ISSUE THREAD

**Issue by NickAnsy** [scsibug/vsmp#1]
Hey there, 
First off I am just getting into coding and wanted to build this for my gf for our anniversary. I am having trouble editing the code to get my screen to work. 
When I run commands through SSH it says it cant find the waveshare module and when i try to run it in Thonny it says it cant find ffmpeg.  Any help would be much appreciated.
![Screen Shot 2020-10-26 at 11 10 49 PM](https://user-images.githubusercontent.com/73515243/97263574-81a32d00-17e0-11eb-81df-d5a1d2edd692.png)
 
![Screen Shot 2020-10-26 at 11 07 32 PM](https://user-images.githubusercontent.com/73515243/97263357-0c375c80-17e0-11eb-8abc-3e5a7ef69249.png)

**Comment by scsibug** [comment]
Hi Nick.  Have you been able to run the demo code provided by waveshare?  There should be a waveshare_epd directory included with that, that has a file specific to your screen size.  I copied that waveshare_epd directory into the same directory as my code, so that the python imports work.

I think you definitely want the demo code to run successfully before you start running your own code - just to validate that the display works and the connections are seated correctly.  The waveshare walkthrough on this screen is here: https://www.waveshare.com/wiki/12.48inch_e-Paper_Module

Happy to help you get this working, it's a fun project.  I don't have any experience with anything other than the 7.5v2 or the 7.8HD screens though.

**Comment by NickAnsy** [comment]
Hey Greg!
Yes I’ve been able to get the demos working.
That’s about all. 
I’d be happy to share my screen with you and show you what I’m dealing with.

**Comment by scsibug** [comment]
Sure, you want to do a zoom session?

Topic: VSMP
Time: Oct 27, 2020 05:30 PM Central Time (US and Canada)

Join Zoom Meeting
https://us05web.zoom.us/j/83670336218?pwd=dVRDYnRBMzMzdzVESGFiank1OTl1QT09

Meeting ID: 836 7033 6218
Passcode: Uv18w6

**Comment by NickAnsy** [comment]
I'd love to, give me about 15 mins as I've stepped away for some air haha.

**Comment by scsibug** [comment]
OK, cool.  I’m just hanging out, so join whenever you’re ready or ping me if it doesn’t work and i’ll set it up a new one.

**Comment by NickAnsy** [comment]
Hey Greg, 
So I made it to line 178/215. 

Epd.display(epd.getbuffer(pil_im))
Attribute error : 'EPD' object has no attribute 'get buffer'

I'm stuck, I don't understand what that means. Struggling to find anything on the web.

**Comment by scsibug** [comment]
The API of the 12" screen code from waveshare appears to be different than that of the 7.5" screen.
If you check out the 7.5" code in [epd7in5_V2.py](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi%26JetsonNano/python/lib/waveshare_epd/epd7in5_V2.py) (which is what most of the code online you find will use), you can see it has `display` and `getbuffer` methods.  But the code for your screen, [epd12in48.py](https://github.com/waveshare/12.48inch-e-paper/blob/master/RaspberryPi/python/lib/epd12in48.py), has no `getbuffer` method - it looks like that is combined with the `display` method, and so you don't even need to worry about it.

Try replacing that failing line with just `epd.display(pil_im)`.

It is probably going to be helpful to look at the 7" and 12" code side by side if you run into other problems with the `epd` driver API, and see what they have changed between the two.  I see a few other minor differences (`clear` vs `Clear`, `init` vs `Init`, `sleep` vs `EPD_sleep`).  So just be aware that they seem to have changed several things.

**Comment by NickAnsy** [comment]
Thanks Greg!
Yeah I caught the ‘clear’ and ‘Init’ differences already. 
Thanks for the tip!

**Comment by NickAnsy** [comment]
So everything is working after that code adjustment and one other small detail I missed. However every once in a while it will display a frame that doesn't use the screen array correctly. I'll include a pic. It's not all the time but it will do it randomly. ![image](https://user-images.githubusercontent.com/73515243/97464724-80682200-18fe-11eb-9604-8108ef23ea0f.jpeg)

**Comment by NickAnsy** [comment]
Also, getting this error when running auto login with console. Not sure why. The file is there. ![image](https://user-images.githubusercontent.com/73515243/97473981-d4780400-1908-11eb-8aa4-093d391cb595.jpeg)

**Comment by scsibug** [comment]
That's a weird one.  I wonder if you can duplicate it with the demo script by itself.  You might try powering everything down, disconnecting power for a minute and trying again.  Possibly check all the connections, maybe some of the flexible connectors?

**Comment by NickAnsy** [comment]
Yeah, it was bizarre. I restarted and it went away. Also have it running totally in headless with The Big Lebowski now. Going to find a frame tomorrow and piece it together.
I’ll be sure to send finish product pics!
Thanks for all your help Greg! Let’s stay in touch!

**Comment by scsibug** [comment]
Oh, that's awesome!  I'd love to see the final product, and definitely let's do that.  Killer job!
